# Generated by Django 5.1.3 on 2024-11-05 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tag', models.CharField(choices=[('sheet_assignment', 'Sheet'), ('lab_assignment', 'Lab'), ('quiz_assignment', 'Quiz'), ('custom_assignment', 'Custom')], default='custom', max_length=20)),
                ('custom_type', models.CharField(blank=True, max_length=20, null=True)),
                ('subject_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subject')),
            ],
        ),
    ]
