# Generated by Django 5.1.1 on 2024-11-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_assignmenttype_alter_assignment_type_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmenttype',
            name='type',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
