# Generated by Django 5.1.4 on 2024-12-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_assignment_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(default="2024-12-12"),
            preserve_default=False,
        ),
    ]
