# Generated by Django 5.1.4 on 2024-12-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_assignment_deadline_alter_materials_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassignment',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
